### ISSUE TITLE
Get shared NFS volume with mote setup on staging

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/zodbot#11]
Currently, in production, we have a shared NFS volume between value01/02 and mote. Meetbot on value dumps the logs after a meeting is finished into the NFS volume, and sends a fedora message. Mote consumes that message, and processes the new logs from the NFS volume.

However, in staging, there was no shared volume, as we previously didnt run staging versions of the bots.

We need to set up this shared volume, get it mounted on mote staging, maubot staging, and value01/02 staging.

**Comment by nirik** [comment]
I think this should be all set now?
